version: "3.8"
services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - main-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    restart: always

  redis:
    image: redis:alpine
    ports:
      - 6380:6379
    networks:
      - main-network
    env_file:
      - .env

  dev:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - main-network
    depends_on:
      - postgres
      - redis
    env_file:
     - .env
    command: ["./wait-for-postgres.sh", "postgres:5432", "--", "sh", "-c", "npm run start:docker-dev"]
    restart: always

  
  prod:
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: ["./wait-for-postgres.sh", "postgres:5432", "--", "sh", "-c", "npm run start:docker-prod"]
    restart: always
    ports:
      - 3000:3000
    networks:
      - main-network
    depends_on:
      - postgres
      - redis

volumes:
  db:
    driver: local

networks:
  main-network:
